# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('liked', models.PositiveIntegerField()),
                ('disliked', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('location', models.TextField()),
                ('going', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('description', models.TextField()),
                ('media_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='junctionEventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
            ],
        ),
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_pic', models.TextField()),
                ('about', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='junctioneventuser',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OurUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OurUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OurUser'),
        ),
    ]
