# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='No title', max_length=100),
            preserve_default=False,
        ),
    ]
