# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
