# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170424_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='profile_pic',
            field=models.TextField(default='static/main/img/userImage.png'),
            preserve_default=False,
        ),
    ]
