# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170425_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='event_set', through='main.junctionEventUser', to='main.OurUser'),
        ),
    ]
