# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='first_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=40, null=True),
        ),
    ]
