# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170426_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='OurUser',
        ),
    ]
